import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormBuilder, FormGroup, FormControl, Validators } from '@angular/forms';
import { HomeComponent } from '../home/home.component';

@Component({
  selector: 'app-vaccination-notifier-form',
  templateUrl: './vaccination-notifier-form.component.html',
  styleUrls: ['./vaccination-notifier-form.component.css']
})
export class VaccinationNotifierFormComponent implements OnInit {
  form: FormGroup;

  name: FormControl = new FormControl("", [Validators.required, Validators.pattern('[a-zA-Z ]*')]);
  age: FormControl = new FormControl("", [Validators.required]);
  email: FormControl = new FormControl("", [Validators.required, Validators.email]);
  contact: FormControl = new FormControl("", [Validators.required, Validators.pattern("^[0-9_-]{10,12}")]);
  state: FormControl = new FormControl("", [Validators.required]);
  city: FormControl = new FormControl("", [Validators.required]);
  pincode: FormControl = new FormControl("");
  locality: FormControl = new FormControl("");
  v_status: boolean = false;

  isLoading: boolean = false; // disable the submit button if loading

  constructor(private formbuilder: FormBuilder, private http: HttpClient, private home: HomeComponent) {
    this.form = this.formbuilder.group({
      name: this.name,
      age: this.age,
      email: this.email,
      contact: this.contact,
      state: this.state,
      city: this.city,
      pincode: this.pincode,
      locality: this.locality
    });
  }

  ngOnInit(): void {
  }

  onBlurOrChange(e: Event) {
    let el: Element = e.target as Element;
    let invalid: Boolean;

    switch (el.getAttribute('name')) {
      case 'name':
        invalid = this.name.invalid;
        break;
      case 'age':
        invalid = this.age.invalid;
        break;
      case 'email':
        invalid = this.email.invalid;
        break;
      case 'contact':
        invalid = this.contact.invalid;
        break;
      case 'state':
        invalid = this.state.invalid;
        break;
      case 'city':
        invalid = this.city.invalid;
        break;
    }

    el.className = invalid ? 'error' : '';
  }


  onSubmit() {
    if (this.form.status == "VALID") {
      this.form.disable(); // disable the form if it's valid to disable multiple submissions

      var formData: any = new FormData();
      formData.append("name", this.form.get("name").value);
      formData.append("age", this.form.get("age").value);
      formData.append("contact", this.form.get("contact").value);
      formData.append("email", this.form.get("email").value);
      formData.append("state", this.form.get("state").value);
      formData.append("city", this.form.get("city").value);
      formData.append("pincode", this.form.get("pincode").value);
      formData.append("locality", this.form.get("locality").value);
      formData.append("v_status", this.v_status);

      this.isLoading = true; // sending the post request async so it's in progress
      this.home.modal = false; // hide the modal on multiple submits

      this.http.post("https://script.google.com/macros/s/AKfycbyM9rbwXyXbjUTkbhlBG3ODFvMEdsXEGcJKRCkDjF7T5R1-uwOU5TauintvEMXpm4sO/exec", formData).subscribe(
        (response) => {
          // choose the response message
          if (response["result"] == "success") {
            this.home.success = true;
          }
          else {
            this.home.success = false;
          }
          
          this.isLoading = false; // re enable the submit button
          this.home.modal = true; // show the response message

          // reset the form after submission
          this.form.reset();
          this.age.setValue("");
          this.state.setValue("");
          this.city.setValue("");

          this.form.enable(); // re enable the form after submission
          
          console.log(response);
        },
        (error) => {
          this.home.success = false;
          
          this.isLoading = false; // re enable the submit button
          this.home.modal = true; // show the response message

          // reset the form after submission
          this.form.reset();
          this.age.setValue("invalid");
          this.state.setValue("invalid");
          this.city.setValue("invalid");

          this.form.enable(); // re enable the form after submission
          
          console.log(error);
        }
      );
    }
  }

  // SELECT STATE AND CITY
  State: any = [{ id: 1 , name: " Andaman and Nicobar Islands " } ,
  { id: 2 , name: " Andhra Pradesh " } ,
  { id: 3 , name: " Arunachal Pradesh " } ,
  { id: 4 , name: " Assam " } ,
  { id: 5 , name: " Bihar " } ,
  { id: 6 , name: " Chandigarh " } ,
  { id: 7 , name: " Chhattisgarh " } ,
  { id: 8 , name: " Dadra and Nagar Haveli " } ,
  { id: 9 , name: " Delhi " } ,
  { id: 10 , name: " Goa " } ,
  { id: 11 , name: " Gujarat " } ,
  { id: 12 , name: " Haryana " } ,
  { id: 13 , name: " Himachal Pradesh " } ,
  { id: 14 , name: " Jammu and Kashmir " } ,
  { id: 15 , name: " Jharkhand " } ,
  { id: 16 , name: " Karnataka " } ,
  { id: 17 , name: " Kerala " } ,
  { id: 18 , name: " Ladakh " } ,
  { id: 19 , name: " Lakshadweep " } ,
  { id: 20 , name: " Madhya Pradesh " } ,
  { id: 21 , name: " Maharashtra " } ,
  { id: 22 , name: " Manipur " } ,
  { id: 23 , name: " Meghalaya " } ,
  { id: 24 , name: " Mizoram " } ,
  { id: 25 , name: " Nagaland " } ,
  { id: 26 , name: " Odisha " } ,
  { id: 27 , name: " Puducherry " } ,
  { id: 28 , name: " Punjab " } ,
  { id: 29 , name: " Rajasthan " } ,
  { id: 30 , name: " Sikkim " } ,
  { id: 31 , name: " Tamil Nadu " } ,
  { id: 32 , name: " Telangana " } ,
  { id: 33 , name: " Tripura " } ,
  { id: 34 , name: " Uttar Pradesh " } ,
  { id: 35 , name: " Uttarakhand " } ,
  { id: 36 , name: " West Bengal " } ,
  { id: 37 , name: " Daman and Diu " } ,
  ]

  City: any = [
    { id: 3 , name: " Nicobar " , state:1 } ,
    { id: 1 , name: " North and Middle Andaman " , state:1 } ,
    { id: 2 , name: " South Andaman " , state:1 } ,
    { id: 9 , name: " Anantapur " , state:2 } ,
    { id: 10 , name: " Chittoor " , state:2 } ,
    { id: 11 , name: " East Godavari " , state:2 } ,
    { id: 5 , name: " Guntur " , state:2 } ,
    { id: 4 , name: " Krishna " , state:2 } ,
    { id: 7 , name: " Kurnool " , state:2 } ,
    { id: 12 , name: " Prakasam " , state:2 } ,
    { id: 13 , name: " Sri Potti Sriramulu Nellore " , state:2 } ,
    { id: 14 , name: " Srikakulam " , state:2 } ,
    { id: 8 , name: " Visakhapatnam " , state:2 } ,
    { id: 15 , name: " Vizianagaram " , state:2 } ,
    { id: 16 , name: " West Godavari " , state:2 } ,
    { id: 6 , name: " YSR District, Kadapa (Cuddapah) " , state:2 } ,
    { id: 22 , name: " Anjaw " , state:3 } ,
    { id: 20 , name: " Changlang " , state:3 } ,
    { id: 25 , name: " Dibang Valley " , state:3 } ,
    { id: 23 , name: " East Kameng " , state:3 } ,
    { id: 42 , name: " East Siang " , state:3 } ,
    { id: 17 , name: " Itanagar Capital Complex " , state:3 } ,
    { id: 24 , name: " Kamle " , state:3 } ,
    { id: 27 , name: " Kra Daadi " , state:3 } ,
    { id: 21 , name: " Kurung Kumey " , state:3 } ,
    { id: 33 , name: " Lepa Rada " , state:3 } ,
    { id: 29 , name: " Lohit " , state:3 } ,
    { id: 40 , name: " Longding " , state:3 } ,
    { id: 31 , name: " Lower Dibang Valley " , state:3 } ,
    { id: 18 , name: " Lower Siang " , state:3 } ,
    { id: 32 , name: " Lower Subansiri " , state:3 } ,
    { id: 36 , name: " Namsai " , state:3 } ,
    { id: 19 , name: " Pakke Kessang " , state:3 } ,
    { id: 39 , name: " Papum Pare " , state:3 } ,
    { id: 35 , name: " Shi Yomi " , state:3 } ,
    { id: 37 , name: " Siang " , state:3 } ,
    { id: 30 , name: " Tawang " , state:3 } ,
    { id: 26 , name: " Tirap " , state:3 } ,
    { id: 34 , name: " Upper Siang " , state:3 } ,
    { id: 41 , name: " Upper Subansiri " , state:3 } ,
    { id: 28 , name: " West Kameng " , state:3 } ,
    { id: 38 , name: " West Siang " , state:3 } ,
    { id: 46 , name: " Baksa " , state:4 } ,
    { id: 47 , name: " Barpeta " , state:4 } ,
    { id: 765 , name: " Biswanath " , state:4 } ,
    { id: 57 , name: " Bongaigaon " , state:4 } ,
    { id: 66 , name: " Cachar " , state:4 } ,
    { id: 766 , name: " Charaideo " , state:4 } ,
    { id: 58 , name: " Chirang " , state:4 } ,
    { id: 48 , name: " Darrang " , state:4 } ,
    { id: 62 , name: " Dhemaji " , state:4 } ,
    { id: 59 , name: " Dhubri " , state:4 } ,
    { id: 43 , name: " Dibrugarh " , state:4 } ,
    { id: 67 , name: " Dima Hasao " , state:4 } ,
    { id: 60 , name: " Goalpara " , state:4 } ,
    { id: 53 , name: " Golaghat " , state:4 } ,
    { id: 68 , name: " Hailakandi " , state:4 } ,
    { id: 764 , name: " Hojai " , state:4 } ,
    { id: 54 , name: " Jorhat " , state:4 } ,
    { id: 49 , name: " Kamrup Metropolitan " , state:4 } ,
    { id: 50 , name: " Kamrup Rural " , state:4 } ,
    { id: 51 , name: " Karbi-Anglong " , state:4 } ,
    { id: 69 , name: " Karimganj " , state:4 } ,
    { id: 61 , name: " Kokrajhar " , state:4 } ,
    { id: 63 , name: " Lakhimpur " , state:4 } ,
    { id: 767 , name: " Majuli " , state:4 } ,
    { id: 55 , name: " Morigaon " , state:4 } ,
    { id: 56 , name: " Nagaon " , state:4 } ,
    { id: 52 , name: " Nalbari " , state:4 } ,
    { id: 44 , name: " Sivasagar " , state:4 } ,
    { id: 64 , name: " Sonitpur " , state:4 } ,
    { id: 768 , name: " South Salmara Mankachar " , state:4 } ,
    { id: 45 , name: " Tinsukia " , state:4 } ,
    { id: 65 , name: " Udalguri " , state:4 } ,
    { id: 769 , name: " West Karbi Anglong " , state:4 } ,
    { id: 74 , name: " Araria " , state:5 } ,
    { id: 78 , name: " Arwal " , state:5 } ,
    { id: 77 , name: " Aurangabad " , state:5 } ,
    { id: 83 , name: " Banka " , state:5 } ,
    { id: 98 , name: " Begusarai " , state:5 } ,
    { id: 82 , name: " Bhagalpur " , state:5 } ,
    { id: 99 , name: " Bhojpur " , state:5 } ,
    { id: 100 , name: " Buxar " , state:5 } ,
    { id: 94 , name: " Darbhanga " , state:5 } ,
    { id: 105 , name: " East Champaran " , state:5 } ,
    { id: 79 , name: " Gaya " , state:5 } ,
    { id: 104 , name: " Gopalganj " , state:5 } ,
    { id: 107 , name: " Jamui " , state:5 } ,
    { id: 91 , name: " Jehanabad " , state:5 } ,
    { id: 80 , name: " Kaimur " , state:5 } ,
    { id: 75 , name: " Katihar " , state:5 } ,
    { id: 101 , name: " Khagaria " , state:5 } ,
    { id: 76 , name: " Kishanganj " , state:5 } ,
    { id: 84 , name: " Lakhisarai " , state:5 } ,
    { id: 70 , name: " Madhepura " , state:5 } ,
    { id: 95 , name: " Madhubani " , state:5 } ,
    { id: 85 , name: " Munger " , state:5 } ,
    { id: 86 , name: " Muzaffarpur " , state:5 } ,
    { id: 90 , name: " Nalanda " , state:5 } ,
    { id: 92 , name: " Nawada " , state:5 } ,
    { id: 97 , name: " Patna " , state:5 } ,
    { id: 73 , name: " Purnia " , state:5 } ,
    { id: 81 , name: " Rohtas " , state:5 } ,
    { id: 71 , name: " Saharsa " , state:5 } ,
    { id: 96 , name: " Samastipur " , state:5 } ,
    { id: 102 , name: " Saran " , state:5 } ,
    { id: 93 , name: " Sheikhpura " , state:5 } ,
    { id: 87 , name: " Sheohar " , state:5 } ,
    { id: 88 , name: " Sitamarhi " , state:5 } ,
    { id: 103 , name: " Siwan " , state:5 } ,
    { id: 72 , name: " Supaul " , state:5 } ,
    { id: 89 , name: " Vaishali " , state:5 } ,
    { id: 106 , name: " West Champaran " , state:5 } ,
    { id: 108 , name: " Chandigarh " , state:6 } ,
    { id: 110 , name: " Balod " , state:7 } ,
    { id: 111 , name: " Baloda bazar " , state:7 } ,
    { id: 112 , name: " Balrampur " , state:7 } ,
    { id: 113 , name: " Bastar " , state:7 } ,
    { id: 114 , name: " Bemetara " , state:7 } ,
    { id: 115 , name: " Bijapur " , state:7 } ,
    { id: 116 , name: " Bilaspur " , state:7 } ,
    { id: 117 , name: " Dantewada " , state:7 } ,
    { id: 118 , name: " Dhamtari " , state:7 } ,
    { id: 119 , name: " Durg " , state:7 } ,
    { id: 120 , name: " Gariaband " , state:7 } ,
    { id: 136 , name: " Gaurela Pendra Marwahi  " , state:7 } ,
    { id: 121 , name: " Janjgir-Champa " , state:7 } ,
    { id: 122 , name: " Jashpur " , state:7 } ,
    { id: 123 , name: " Kanker " , state:7 } ,
    { id: 135 , name: " Kawardha " , state:7 } ,
    { id: 124 , name: " Kondagaon " , state:7 } ,
    { id: 125 , name: " Korba " , state:7 } ,
    { id: 126 , name: " Koriya " , state:7 } ,
    { id: 127 , name: " Mahasamund " , state:7 } ,
    { id: 128 , name: " Mungeli " , state:7 } ,
    { id: 129 , name: " Narayanpur " , state:7 } ,
    { id: 130 , name: " Raigarh " , state:7 } ,
    { id: 109 , name: " Raipur " , state:7 } ,
    { id: 131 , name: " Rajnandgaon " , state:7 } ,
    { id: 132 , name: " Sukma " , state:7 } ,
    { id: 133 , name: " Surajpur " , state:7 } ,
    { id: 134 , name: " Surguja " , state:7 } ,
    { id: 137 , name: " Dadra and Nagar Haveli " , state:8 } ,
    { id: 141 , name: " Central Delhi " , state:9 } ,
    { id: 145 , name: " East Delhi " , state:9 } ,
    { id: 140 , name: " New Delhi " , state:9 } ,
    { id: 146 , name: " North Delhi " , state:9 } ,
    { id: 147 , name: " North East Delhi " , state:9 } ,
    { id: 143 , name: " North West Delhi " , state:9 } ,
    { id: 148 , name: " Shahdara " , state:9 } ,
    { id: 149 , name: " South Delhi " , state:9 } ,
    { id: 144 , name: " South East Delhi " , state:9 } ,
    { id: 150 , name: " South West Delhi " , state:9 } ,
    { id: 142 , name: " West Delhi " , state:9 } ,
    { id: 151 , name: " North Goa " , state:10 } ,
    { id: 152 , name: " South Goa " , state:10 } ,    
    { id: 154 , name: " Ahmedabad " , state:11 } ,
    { id: 770 , name: " Ahmedabad Corporation " , state:11 } ,
    { id: 174 , name: " Amreli " , state:11 } ,
    { id: 179 , name: " Anand " , state:11 } ,
    { id: 158 , name: " Aravalli " , state:11 } ,
    { id: 159 , name: " Banaskantha " , state:11 } ,
    { id: 180 , name: " Bharuch " , state:11 } ,
    { id: 175 , name: " Bhavnagar " , state:11 } ,
    { id: 771 , name: " Bhavnagar Corporation " , state:11 } ,
    { id: 176 , name: " Botad " , state:11 } ,
    { id: 181 , name: " Chhotaudepur " , state:11 } ,
    { id: 182 , name: " Dahod " , state:11 } ,
    { id: 163 , name: " Dang " , state:11 } ,
    { id: 168 , name: " Devbhumi Dwaraka " , state:11 } ,
    { id: 153 , name: " Gandhinagar " , state:11 } ,
    { id: 772 , name: " Gandhinagar Corporation " , state:11 } ,
    { id: 177 , name: " Gir Somnath " , state:11 } ,
    { id: 169 , name: " Jamnagar " , state:11 } ,
    { id: 773 , name: " Jamnagar Corporation " , state:11 } ,
    { id: 178 , name: " Junagadh " , state:11 } ,
    { id: 774 , name: " Junagadh Corporation " , state:11 } ,
    { id: 156 , name: " Kheda " , state:11 } ,
    { id: 170 , name: " Kutch " , state:11 } ,
    { id: 183 , name: " Mahisagar " , state:11 } ,
    { id: 160 , name: " Mehsana " , state:11 } ,
    { id: 171 , name: " Morbi " , state:11 } ,
    { id: 184 , name: " Narmada " , state:11 } ,
    { id: 164 , name: " Navsari " , state:11 } ,
    { id: 185 , name: " Panchmahal " , state:11 } ,
    { id: 161 , name: " Patan " , state:11 } ,
    { id: 172 , name: " Porbandar " , state:11 } ,
    { id: 173 , name: " Rajkot " , state:11 } ,
    { id: 775 , name: " Rajkot Corporation " , state:11 } ,
    { id: 162 , name: " Sabarkantha " , state:11 } ,
    { id: 165 , name: " Surat " , state:11 } ,
    { id: 776 , name: " Surat Corporation " , state:11 } ,
    { id: 157 , name: " Surendranagar " , state:11 } ,
    { id: 166 , name: " Tapi " , state:11 } ,
    { id: 155 , name: " Vadodara " , state:11 } ,
    { id: 777 , name: " Vadodara Corporation " , state:11 } ,
    { id: 167 , name: " Valsad " , state:11 } ,
    { id: 193 , name: " Ambala " , state:12 } ,
    { id: 200 , name: " Bhiwani " , state:12 } ,
    { id: 201 , name: " Charkhi Dadri " , state:12 } ,
    { id: 199 , name: " Faridabad " , state:12 } ,
    { id: 196 , name: " Fatehabad " , state:12 } ,
    { id: 188 , name: " Gurgaon " , state:12 } ,
    { id: 191 , name: " Hisar " , state:12 } ,
    { id: 189 , name: " Jhajjar " , state:12 } ,
    { id: 204 , name: " Jind " , state:12 } ,
    { id: 190 , name: " Kaithal " , state:12 } ,
    { id: 203 , name: " Karnal " , state:12 } ,
    { id: 186 , name: " Kurukshetra " , state:12 } ,
    { id: 206 , name: " Mahendragarh " , state:12 } ,
    { id: 205 , name: " Nuh " , state:12 } ,
    { id: 207 , name: " Palwal " , state:12 } ,
    { id: 187 , name: " Panchkula " , state:12 } ,
    { id: 195 , name: " Panipat " , state:12 } ,
    { id: 202 , name: " Rewari " , state:12 } ,
    { id: 192 , name: " Rohtak " , state:12 } ,
    { id: 194 , name: " Sirsa " , state:12 } ,
    { id: 198 , name: " Sonipat " , state:12 } ,
    { id: 197 , name: " Yamunanagar " , state:12 } ,    
    { id: 219 , name: " Bilaspur " , state:13 } ,
    { id: 214 , name: " Chamba " , state:13 } ,
    { id: 217 , name: " Hamirpur " , state:13 } ,
    { id: 213 , name: " Kangra " , state:13 } ,
    { id: 216 , name: " Kinnaur " , state:13 } ,
    { id: 211 , name: " Kullu " , state:13 } ,
    { id: 210 , name: " Lahaul Spiti " , state:13 } ,
    { id: 215 , name: " Mandi " , state:13 } ,
    { id: 208 , name: " Shimla " , state:13 } ,
    { id: 212 , name: " Sirmaur " , state:13 } ,
    { id: 209 , name: " Solan " , state:13 } ,
    { id: 218 , name: " Una " , state:13 } ,
    { id: 224 , name: " Anantnag " , state:14 } ,
    { id: 223 , name: " Bandipore " , state:14 } ,
    { id: 225 , name: " Baramulla " , state:14 } ,
    { id: 229 , name: " Budgam " , state:14 } ,
    { id: 232 , name: " Doda " , state:14 } ,
    { id: 228 , name: " Ganderbal " , state:14 } ,
    { id: 230 , name: " Jammu " , state:14 } ,
    { id: 234 , name: " Kathua " , state:14 } ,
    { id: 231 , name: " Kishtwar " , state:14 } ,
    { id: 221 , name: " Kulgam " , state:14 } ,
    { id: 226 , name: " Kupwara " , state:14 } ,
    { id: 238 , name: " Poonch " , state:14 } ,
    { id: 227 , name: " Pulwama " , state:14 } ,
    { id: 237 , name: " Rajouri " , state:14 } ,
    { id: 235 , name: " Ramban " , state:14 } ,
    { id: 239 , name: " Reasi " , state:14 } ,
    { id: 236 , name: " Samba " , state:14 } ,
    { id: 222 , name: " Shopian " , state:14 } ,
    { id: 220 , name: " Srinagar " , state:14 } ,
    { id: 233 , name: " Udhampur " , state:14 } ,
    { id: 242 , name: " Bokaro " , state:15 } ,
    { id: 245 , name: " Chatra " , state:15 } ,
    { id: 253 , name: " Deoghar " , state:15 } ,
    { id: 257 , name: " Dhanbad " , state:15 } ,
    { id: 258 , name: " Dumka " , state:15 } ,
    { id: 247 , name: " East Singhbhum " , state:15 } ,
    { id: 243 , name: " Garhwa " , state:15 } ,
    { id: 256 , name: " Giridih " , state:15 } ,
    { id: 262 , name: " Godda " , state:15 } ,
    { id: 251 , name: " Gumla " , state:15 } ,
    { id: 255 , name: " Hazaribagh " , state:15 } ,
    { id: 259 , name: " Jamtara " , state:15 } ,
    { id: 252 , name: " Khunti " , state:15 } ,
    { id: 241 , name: " Koderma " , state:15 } ,
    { id: 244 , name: " Latehar " , state:15 } ,
    { id: 250 , name: " Lohardaga " , state:15 } ,
    { id: 261 , name: " Pakur " , state:15 } ,
    { id: 246 , name: " Palamu " , state:15 } ,
    { id: 254 , name: " Ramgarh " , state:15 } ,
    { id: 240 , name: " Ranchi " , state:15 } ,
    { id: 260 , name: " Sahebganj " , state:15 } ,
    { id: 248 , name: " Seraikela Kharsawan " , state:15 } ,
    { id: 249 , name: " Simdega " , state:15 } ,
    { id: 270 , name: " Bagalkot " , state:16 } ,
    { id: 276 , name: " Bangalore Rural " , state:16 } ,
    { id: 265 , name: " Bangalore Urban " , state:16 } ,
    { id: 294 , name: " BBMP " , state:16 } ,
    { id: 264 , name: " Belgaum " , state:16 } ,
    { id: 274 , name: " Bellary " , state:16 } ,
    { id: 272 , name: " Bidar " , state:16 } ,
    { id: 271 , name: " Chamarajanagar " , state:16 } ,
    { id: 273 , name: " Chikamagalur " , state:16 } ,
    { id: 291 , name: " Chikkaballapur " , state:16 } ,
    { id: 268 , name: " Chitradurga " , state:16 } ,
    { id: 269 , name: " Dakshina Kannada " , state:16 } ,
    { id: 275 , name: " Davanagere " , state:16 } ,
    { id: 278 , name: " Dharwad " , state:16 } ,
    { id: 280 , name: " Gadag " , state:16 } ,
    { id: 267 , name: " Gulbarga " , state:16 } ,
    { id: 289 , name: " Hassan " , state:16 } ,
    { id: 279 , name: " Haveri " , state:16 } ,
    { id: 283 , name: " Kodagu " , state:16 } ,
    { id: 277 , name: " Kolar " , state:16 } ,
    { id: 282 , name: " Koppal " , state:16 } ,
    { id: 290 , name: " Mandya " , state:16 } ,
    { id: 266 , name: " Mysore " , state:16 } ,
    { id: 284 , name: " Raichur " , state:16 } ,
    { id: 292 , name: " Ramanagara " , state:16 } ,
    { id: 287 , name: " Shimoga " , state:16 } ,
    { id: 288 , name: " Tumkur " , state:16 } ,
    { id: 286 , name: " Udupi " , state:16 } ,
    { id: 281 , name: " Uttar Kannada " , state:16 } ,
    { id: 293 , name: " Vijayapura " , state:16 } ,
    { id: 285 , name: " Yadgir " , state:16 } ,
    { id: 622 , name: " Agra " , state:34 } ,
    { id: 623 , name: " Aligarh " , state:34 } ,
    { id: 625 , name: " Ambedkar Nagar " , state:34 } ,
    { id: 626 , name: " Amethi " , state:34 } ,
    { id: 627 , name: " Amroha " , state:34 } ,
    { id: 628 , name: " Auraiya " , state:34 } ,
    { id: 646 , name: " Ayodhya " , state:34 } ,
    { id: 629 , name: " Azamgarh " , state:34 } ,
    { id: 630 , name: " Badaun " , state:34 } ,
    { id: 631 , name: " Baghpat " , state:34 } ,
    { id: 632 , name: " Bahraich " , state:34 } ,
    { id: 633 , name: " Balarampur " , state:34 } ,
    { id: 634 , name: " Ballia " , state:34 } ,
    { id: 635 , name: " Banda " , state:34 } ,
    { id: 636 , name: " Barabanki " , state:34 } ,
    { id: 637 , name: " Bareilly " , state:34 } ,
    { id: 638 , name: " Basti " , state:34 } ,
    { id: 687 , name: " Bhadohi " , state:34 } ,
    { id: 639 , name: " Bijnour " , state:34 } ,
    { id: 640 , name: " Bulandshahr " , state:34 } ,
    { id: 641 , name: " Chandauli " , state:34 } ,
    { id: 642 , name: " Chitrakoot " , state:34 } ,
    { id: 643 , name: " Deoria " , state:34 } ,
    { id: 644 , name: " Etah " , state:34 } ,
    { id: 645 , name: " Etawah " , state:34 } ,
    { id: 647 , name: " Farrukhabad " , state:34 } ,
    { id: 648 , name: " Fatehpur " , state:34 } ,
    { id: 649 , name: " Firozabad " , state:34 } ,
    { id: 650 , name: " Gautam Buddha Nagar " , state:34 } ,
    { id: 651 , name: " Ghaziabad " , state:34 } ,
    { id: 652 , name: " Ghazipur " , state:34 } ,
    { id: 653 , name: " Gonda " , state:34 } ,
    { id: 654 , name: " Gorakhpur " , state:34 } ,
    { id: 655 , name: " Hamirpur " , state:34 } ,
    { id: 656 , name: " Hapur " , state:34 } ,
    { id: 657 , name: " Hardoi " , state:34 } ,
    { id: 658 , name: " Hathras " , state:34 } ,
    { id: 659 , name: " Jalaun " , state:34 } ,
    { id: 660 , name: " Jaunpur " , state:34 } ,
    { id: 661 , name: " Jhansi " , state:34 } ,
    { id: 662 , name: " Kannauj " , state:34 } ,
    { id: 663 , name: " Kanpur Dehat " , state:34 } ,
    { id: 664 , name: " Kanpur Nagar " , state:34 } ,
    { id: 665 , name: " Kasganj " , state:34 } ,
    { id: 666 , name: " Kaushambi " , state:34 } ,
    { id: 667 , name: " Kushinagar " , state:34 } ,
    { id: 668 , name: " Lakhimpur Kheri " , state:34 } ,
    { id: 669 , name: " Lalitpur " , state:34 } ,
    { id: 670 , name: " Lucknow " , state:34 } ,
    { id: 671 , name: " Maharajganj " , state:34 } ,
    { id: 672 , name: " Mahoba " , state:34 } ,
    { id: 673 , name: " Mainpuri " , state:34 } ,
    { id: 674 , name: " Mathura " , state:34 } ,
    { id: 675 , name: " Mau " , state:34 } ,
    { id: 676 , name: " Meerut " , state:34 } ,
    { id: 677 , name: " Mirzapur " , state:34 } ,
    { id: 678 , name: " Moradabad " , state:34 } ,
    { id: 679 , name: " Muzaffarnagar " , state:34 } ,
    { id: 680 , name: " Pilibhit " , state:34 } ,
    { id: 682 , name: " Pratapgarh " , state:34 } ,
    { id: 624 , name: " Prayagraj " , state:34 } ,
    { id: 681 , name: " Raebareli " , state:34 } ,
    { id: 683 , name: " Rampur " , state:34 } ,{ id: 684 , name: " Saharanpur " , state:34 } ,
    { id: 685 , name: " Sambhal " , state:34 } ,
    { id: 686 , name: " Sant Kabir Nagar " , state:34 } ,
    { id: 688 , name: " Shahjahanpur " , state:34 } ,
    { id: 689 , name: " Shamli " , state:34 } ,
    { id: 690 , name: " Shravasti " , state:34 } ,
    { id: 691 , name: " Siddharthnagar " , state:34 } ,
    { id: 692 , name: " Sitapur " , state:34 } ,
    { id: 693 , name: " Sonbhadra " , state:34 } ,
    { id: 694 , name: " Sultanpur " , state:34 } ,
    { id: 695 , name: " Unnao " , state:34 } ,
    { id: 696 , name: " Varanasi " , state:34 } ,
    { id: 614 , name: " Dhalai " , state:33 } ,
    { id: 615 , name: " Gomati " , state:33 } ,
    { id: 616 , name: " Khowai " , state:33 } ,
    { id: 617 , name: " North Tripura " , state:33 } ,
    { id: 618 , name: " Sepahijala " , state:33 } ,
    { id: 619 , name: " South Tripura " , state:33 } ,
    { id: 620 , name: " Unakoti " , state:33 } ,
    { id: 621 , name: " West Tripura " , state:33 } ,
    { id: 582 , name: " Adilabad " , state:32 } ,
    { id: 583 , name: " Bhadradri Kothagudem " , state:32 } ,
    { id: 581 , name: " Hyderabad " , state:32 } ,
    { id: 584 , name: " Jagtial " , state:32 } ,
    { id: 585 , name: " Jangaon " , state:32 } ,
    { id: 586 , name: " Jayashankar Bhupalpally " , state:32 } ,
    { id: 587 , name: " Jogulamba Gadwal " , state:32 } ,
    { id: 588 , name: " Kamareddy " , state:32 } ,
    { id: 589 , name: " Karimnagar " , state:32 } ,
    { id: 590 , name: " Khammam " , state:32 } ,
    { id: 591 , name: " Kumuram Bheem " , state:32 } ,
    { id: 592 , name: " Mahabubabad " , state:32 } ,
    { id: 593 , name: " Mahabubnagar " , state:32 } ,
    { id: 594 , name: " Mancherial " , state:32 } ,
    { id: 595 , name: " Medak " , state:32 } ,
    { id: 596 , name: " Medchal " , state:32 } ,
    { id: 612 , name: " Mulugu " , state:32 } ,
    { id: 597 , name: " Nagarkurnool " , state:32 } ,
    { id: 598 , name: " Nalgonda " , state:32 } ,
    { id: 613 , name: " Narayanpet " , state:32 } ,
    { id: 599 , name: " Nirmal " , state:32 } ,
    { id: 600 , name: " Nizamabad " , state:32 } ,
    { id: 601 , name: " Peddapalli " , state:32 } ,
    { id: 602 , name: " Rajanna Sircilla " , state:32 } ,
    { id: 603 , name: " Rangareddy " , state:32 } ,
    { id: 604 , name: " Sangareddy " , state:32 } ,
    { id: 605 , name: " Siddipet " , state:32 } ,
    { id: 606 , name: " Suryapet " , state:32 } ,
    { id: 607 , name: " Vikarabad " , state:32 } ,
    { id: 608 , name: " Wanaparthy " , state:32 } ,
    { id: 609 , name: " Warangal(Rural) " , state:32 } ,
    { id: 610 , name: " Warangal(Urban) " , state:32 } ,
    { id: 611 , name: " Yadadri Bhuvanagiri " , state:32 } ,
    { id: 779 , name: " Aranthangi " , state:31 } ,
    { id: 555 , name: " Ariyalur " , state:31 } ,
    { id: 578 , name: " Attur " , state:31 } ,
    { id: 565 , name: " Chengalpet " , state:31 } ,
    { id: 571 , name: " Chennai " , state:31 } ,
    { id: 778 , name: " Cheyyar " , state:31 } ,
    { id: 539 , name: " Coimbatore " , state:31 } ,
    { id: 547 , name: " Cuddalore " , state:31 } ,
    { id: 566 , name: " Dharmapuri " , state:31 } ,
    { id: 556 , name: " Dindigul " , state:31 } ,
    { id: 563 , name: " Erode " , state:31 } ,
    { id: 552 , name: " Kallakurichi " , state:31 } ,
    { id: 557 , name: " Kanchipuram " , state:31 } ,
    { id: 544 , name: " Kanyakumari " , state:31 } ,
    { id: 559 , name: " Karur " , state:31 } ,
    { id: 780 , name: " Kovilpatti " , state:31 } ,
    { id: 562 , name: " Krishnagiri " , state:31 } ,
    { id: 540 , name: " Madurai " , state:31 } ,
    { id: 576 , name: " Nagapattinam " , state:31 } ,
    { id: 558 , name: " Namakkal " , state:31 } ,
    { id: 577 , name: " Nilgiris " , state:31 } ,
    { id: 564 , name: " Palani " , state:31 } ,
    { id: 573 , name: " Paramakudi " , state:31 } ,
    { id: 570 , name: " Perambalur " , state:31 } ,
    { id: 575 , name: " Poonamallee " , state:31 } ,
    { id: 546 , name: " Pudukkottai " , state:31 } ,
    { id: 567 , name: " Ramanathapuram " , state:31 } ,
    { id: 781 , name: " Ranipet " , state:31 } ,
    { id: 545 , name: " Salem " , state:31 } ,
    { id: 561 , name: " Sivaganga " , state:31 } ,
    { id: 580 , name: " Sivakasi " , state:31 } ,
    { id: 551 , name: " Tenkasi " , state:31 } ,
    { id: 541 , name: " Thanjavur " , state:31 } ,
    { id: 569 , name: " Theni " , state:31 } ,
    { id: 554 , name: " Thoothukudi (Tuticorin) " , state:31 } ,
    { id: 560 , name: " Tiruchirappalli " , state:31 } ,
    { id: 548 , name: " Tirunelveli " , state:31 } ,
    { id: 550 , name: " Tirupattur " , state:31 } ,
    { id: 568 , name: " Tiruppur " , state:31 } ,
    { id: 572 , name: " Tiruvallur " , state:31 } ,
    { id: 553 , name: " Tiruvannamalai " , state:31 } ,
    { id: 574 , name: " Tiruvarur " , state:31 } ,
    { id: 543 , name: " Vellore " , state:31 } ,
    { id: 542 , name: " Viluppuram " , state:31 } ,
    { id: 549 , name: " Virudhunagar " , state:31 } ,
    { id: 535 , name: " East Sikkim " , state:30 } ,
    { id: 537 , name: " North Sikkim " , state:30 } ,
    { id: 538 , name: " South Sikkim " , state:30 } ,
    { id: 536 , name: " West Sikkim " , state:30 } ,
    { id: 507 , name: " Ajmer " , state:29 } ,
    { id: 512 , name: " Alwar " , state:29 } ,
    { id: 519 , name: " Banswara " , state:29 } ,
    { id: 516 , name: " Baran " , state:29 } ,
    { id: 528 , name: " Barmer " , state:29 } ,
    { id: 508 , name: " Bharatpur " , state:29 } ,
    { id: 523 , name: " Bhilwara " , state:29 } ,
    { id: 501 , name: " Bikaner " , state:29 } ,
    { id: 514 , name: " Bundi " , state:29 } ,
    { id: 521 , name: " Chittorgarh " , state:29 } ,
    { id: 530 , name: " Churu " , state:29 } ,
    { id: 511 , name: " Dausa " , state:29 } ,
    { id: 524 , name: " Dholpur " , state:29 } ,
    { id: 520 , name: " Dungarpur " , state:29 } ,
    { id: 517 , name: " Hanumangarh " , state:29 } ,
    { id: 505 , name: " Jaipur I " , state:29 } ,
    { id: 506 , name: " Jaipur II " , state:29 } ,
    { id: 527 , name: " Jaisalmer " , state:29 } ,
    { id: 533 , name: " Jalore " , state:29 } ,
    { id: 515 , name: " Jhalawar " , state:29 } ,
    { id: 510 , name: " Jhunjhunu " , state:29 } ,
    { id: 502 , name: " Jodhpur " , state:29 } ,
    { id: 525 , name: " Karauli " , state:29 } ,
    { id: 503 , name: " Kota " , state:29 } ,
    { id: 532 , name: " Nagaur " , state:29 } ,
    { id: 529 , name: " Pali " , state:29 } ,
    { id: 522 , name: " Pratapgarh " , state:29 } ,
    { id: 518 , name: " Rajsamand " , state:29 } ,
    { id: 534 , name: " Sawai Madhopur " , state:29 } ,
    { id: 513 , name: " Sikar " , state:29 } ,
    { id: 531 , name: " Sirohi " , state:29 } ,
    { id: 509 , name: " Sri Ganganagar " , state:29 } ,
    { id: 526 , name: " Tonk " , state:29 } ,
    { id: 504 , name: " Udaipur " , state:29 } ,
    { id: 485 , name: " Amritsar " , state:28 } ,
    { id: 483 , name: " Barnala " , state:28 } ,
    { id: 493 , name: " Bathinda " , state:28 } ,
    { id: 499 , name: " Faridkot " , state:28 } ,
    { id: 484 , name: " Fatehgarh Sahib " , state:28 } ,
    { id: 487 , name: " Fazilka " , state:28 } ,
    { id: 480 , name: " Ferozpur " , state:28 } ,
    { id: 489 , name: " Gurdaspur " , state:28 } ,
    { id: 481 , name: " Hoshiarpur " , state:28 } ,
    { id: 492 , name: " Jalandhar " , state:28 } ,
    { id: 479 , name: " Kapurthala " , state:28 } ,
    { id: 488 , name: " Ludhiana " , state:28 } ,
    { id: 482 , name: " Mansa " , state:28 } ,
    { id: 491 , name: " Moga " , state:28 } ,
    { id: 486 , name: " Pathankot " , state:28 } ,
    { id: 494 , name: " Patiala " , state:28 } ,
    { id: 497 , name: " Rup Nagar " , state:28 } ,
    { id: 498 , name: " Sangrur " , state:28 } ,
    { id: 496 , name: " SAS Nagar " , state:28 } ,
    { id: 500 , name: " SBS Nagar " , state:28 } ,
    { id: 490 , name: " Sri Muktsar Sahib " , state:28 } ,
    { id: 495 , name: " Tarn Taran " , state:28 } ,
    { id: 476 , name: " Karaikal " , state:27 } ,
    { id: 477 , name: " Mahe " , state:27 } ,
    { id: 475 , name: " Puducherry " , state:27 } ,
    { id: 478 , name: " Yanam " , state:27 } ,
    { id: 445 , name: " Angul " , state:26 } ,
    { id: 448 , name: " Balangir " , state:26 } ,
    { id: 447 , name: " Balasore " , state:26 } ,
    { id: 472 , name: " Bargarh " , state:26 } ,
    { id: 454 , name: " Bhadrak " , state:26 } ,
    { id: 468 , name: " Boudh " , state:26 } ,
    { id: 457 , name: " Cuttack " , state:26 } ,
    { id: 473 , name: " Deogarh " , state:26 } ,
    { id: 458 , name: " Dhenkanal " , state:26 } ,
    { id: 467 , name: " Gajapati " , state:26 } ,
    { id: 449 , name: " Ganjam " , state:26 } ,
    { id: 459 , name: " Jagatsinghpur " , state:26 } ,
    { id: 460 , name: " Jajpur " , state:26 } ,
    { id: 474 , name: " Jharsuguda " , state:26 } ,
    { id: 464 , name: " Kalahandi " , state:26 } ,
    { id: 450 , name: " Kandhamal " , state:26 } ,
    { id: 461 , name: " Kendrapara " , state:26 } ,
    { id: 455 , name: " Kendujhar " , state:26 } ,
    { id: 446 , name: " Khurda " , state:26 } ,
    { id: 451 , name: " Koraput " , state:26 } ,
    { id: 469 , name: " Malkangiri " , state:26 } ,
    { id: 456 , name: " Mayurbhanj " , state:26 } ,
    { id: 470 , name: " Nabarangpur " , state:26 } ,
    { id: 462 , name: " Nayagarh " , state:26 } ,
    { id: 465 , name: " Nuapada " , state:26 } ,
    { id: 463 , name: " Puri " , state:26 } ,
    { id: 471 , name: " Rayagada " , state:26 } ,
    { id: 452 , name: " Sambalpur " , state:26 } ,
    { id: 466 , name: " Subarnapur " , state:26 } ,
    { id: 453 , name: " Sundargarh " , state:26 } ,
    { id: 434 , name: " Dimapur " , state:25 } ,
    { id: 444 , name: " Kiphire " , state:25 } ,
    { id: 441 , name: " Kohima " , state:25 } ,
    { id: 438 , name: " Longleng " , state:25 } ,
    { id: 437 , name: " Mokokchung " , state:25 } ,
    { id: 439 , name: " Mon " , state:25 } ,
    { id: 435 , name: " Peren " , state:25 } ,
    { id: 443 , name: " Phek " , state:25 } ,
    { id: 440 , name: " Tuensang " , state:25 } ,
    { id: 436 , name: " Wokha " , state:25 } ,
    { id: 442 , name: " Zunheboto " , state:25 } ,
    { id: 425 , name: " Aizawl East " , state:24 } ,
    { id: 426 , name: " Aizawl West " , state:24 } ,
    { id: 429 , name: " Champhai " , state:24 } ,
    { id: 428 , name: " Kolasib " , state:24 } ,
    { id: 432 , name: " Lawngtlai " , state:24 } ,
    { id: 431 , name: " Lunglei " , state:24 } ,
    { id: 427 , name: " Mamit " , state:24 } ,
    { id: 430 , name: " Serchhip " , state:24 } ,
    { id: 433 , name: " Siaha " , state:24 } ,
    { id: 424 , name: " East Garo Hills " , state:23 } ,
    { id: 418 , name: " East Jaintia Hills " , state:23 } ,
    { id: 414 , name: " East Khasi Hills " , state:23 } ,
    { id: 423 , name: " North Garo Hills " , state:23 } ,
    { id: 417 , name: " Ri-Bhoi " , state:23 } ,
    { id: 421 , name: " South Garo Hills " , state:23 } ,
    { id: 422 , name: " South West Garo Hills " , state:23 } ,
    { id: 415 , name: " South West Khasi Hills " , state:23 } ,
    { id: 420 , name: " West Garo Hills " , state:23 } ,
    { id: 416 , name: " West Jaintia Hills " , state:23 } ,
    { id: 419 , name: " West Khasi Hills " , state:23 } ,
    { id: 398 , name: " Bishnupur " , state:22 } ,
    { id: 399 , name: " Chandel " , state:22 } ,
    { id: 400 , name: " Churachandpur " , state:22 } ,
    { id: 401 , name: " Imphal East " , state:22 } ,
    { id: 402 , name: " Imphal West " , state:22 } ,
    { id: 410 , name: " Jiribam " , state:22 } ,
    { id: 413 , name: " Kakching " , state:22 } ,
    { id: 409 , name: " Kamjong " , state:22 } ,
    { id: 408 , name: " Kangpokpi " , state:22 } ,
    { id: 412 , name: " Noney " , state:22 } ,
    { id: 411 , name: " Pherzawl " , state:22 } ,
    { id: 403 , name: " Senapati " , state:22 } ,
    { id: 404 , name: " Tamenglong " , state:22 } ,
    { id: 407 , name: " Tengnoupal " , state:22 } ,
    { id: 405 , name: " Thoubal " , state:22 } ,
    { id: 406 , name: " Ukhrul " , state:22 } ,
    { id: 391 , name: " Ahmednagar " , state:21 } ,
    { id: 364 , name: " Akola " , state:21 } ,
    { id: 366 , name: " Amravati " , state:21 } ,
    { id: 397 , name: " Aurangabad  " , state:21 } ,
    { id: 384 , name: " Beed " , state:21 } ,
    { id: 370 , name: " Bhandara " , state:21 } ,
    { id: 367 , name: " Buldhana " , state:21 } ,
    { id: 380 , name: " Chandrapur " , state:21 } ,
    { id: 388 , name: " Dhule " , state:21 } ,
    { id: 379 , name: " Gadchiroli " , state:21 } ,
    { id: 378 , name: " Gondia " , state:21 } ,
    { id: 386 , name: " Hingoli " , state:21 } ,
    { id: 390 , name: " Jalgaon " , state:21 } ,
    { id: 396 , name: " Jalna " , state:21 } ,
    { id: 371 , name: " Kolhapur " , state:21 } ,
    { id: 383 , name: " Latur " , state:21 } ,
    { id: 395 , name: " Mumbai " , state:21 } ,
    { id: 365 , name: " Nagpur " , state:21 } ,
    { id: 382 , name: " Nanded " , state:21 } ,
    { id: 387 , name: " Nandurbar " , state:21 } ,
    { id: 389 , name: " Nashik " , state:21 } ,
    { id: 381 , name: " Osmanabad " , state:21 } ,
    { id: 394 , name: " Palghar " , state:21 } ,
    { id: 385 , name: " Parbhani " , state:21 } ,
    { id: 363 , name: " Pune " , state:21 } ,
    { id: 393 , name: " Raigad " , state:21 } ,
    { id: 372 , name: " Ratnagiri " , state:21 } ,
    { id: 373 , name: " Sangli " , state:21 } ,
    { id: 376 , name: " Satara " , state:21 } ,
    { id: 374 , name: " Sindhudurg " , state:21 } ,
    { id: 375 , name: " Solapur " , state:21 } ,
    { id: 392 , name: " Thane " , state:21 } ,
    { id: 377 , name: " Wardha " , state:21 } ,
    { id: 369 , name: " Washim " , state:21 } ,
    { id: 368 , name: " Yavatmal " , state:21 } ,
    { id: 320 , name: " Agar " , state:20 } ,
    { id: 357 , name: " Alirajpur " , state:20 } ,
    { id: 334 , name: " Anuppur " , state:20 } ,
    { id: 354 , name: " Ashoknagar " , state:20 } ,
    { id: 338 , name: " Balaghat " , state:20 } ,
    { id: 343 , name: " Barwani " , state:20 } ,
    { id: 362 , name: " Betul " , state:20 } ,
    { id: 351 , name: " Bhind " , state:20 } ,
    { id: 312 , name: " Bhopal " , state:20 } ,
    { id: 342 , name: " Burhanpur " , state:20 } ,
    { id: 328 , name: " Chhatarpur " , state:20 } ,
    { id: 337 , name: " Chhindwara " , state:20 } ,
    { id: 327 , name: " Damoh " , state:20 } ,
    { id: 350 , name: " Datia " , state:20 } ,
    { id: 324 , name: " Dewas " , state:20 } ,
    { id: 341 , name: " Dhar " , state:20 } ,
    { id: 336 , name: " Dindori " , state:20 } ,
    { id: 348 , name: " Guna " , state:20 } ,
    { id: 313 , name: " Gwalior " , state:20 } ,
    { id: 361 , name: " Harda " , state:20 } ,
    { id: 360 , name: " Hoshangabad " , state:20 } ,
    { id: 314 , name: " Indore " , state:20 } ,
    { id: 315 , name: " Jabalpur " , state:20 } ,
    { id: 340 , name: " Jhabua " , state:20 } ,
    { id: 353 , name: " Katni " , state:20 } ,
    { id: 339 , name: " Khandwa " , state:20 } ,
    { id: 344 , name: " Khargone " , state:20 } ,
    { id: 335 , name: " Mandla " , state:20 } ,
    { id: 319 , name: " Mandsaur " , state:20 } ,
    { id: 347 , name: " Morena " , state:20 } ,
    { id: 352 , name: " Narsinghpur " , state:20 } ,
    { id: 323 , name: " Neemuch " , state:20 } ,
    { id: 326 , name: " Panna " , state:20 } ,
    { id: 359 , name: " Raisen " , state:20 } ,
    { id: 358 , name: " Rajgarh " , state:20 } ,
    { id: 322 , name: " Ratlam " , state:20 } ,
    { id: 316 , name: " Rewa " , state:20 } ,
    { id: 317 , name: " Sagar " , state:20 } ,
    { id: 333 , name: " Satna " , state:20 } ,
    { id: 356 , name: " Sehore " , state:20 } ,
    { id: 349 , name: " Seoni " , state:20 } ,
    { id: 332 , name: " Shahdol " , state:20 } ,
    { id: 321 , name: " Shajapur " , state:20 } ,
    { id: 346 , name: " Sheopur " , state:20 } ,
    { id: 345 , name: " Shivpuri " , state:20 } ,
    { id: 331 , name: " Sidhi " , state:20 } ,
    { id: 330 , name: " Singrauli " , state:20 } ,
    { id: 325 , name: " Tikamgarh " , state:20 } ,
    { id: 318 , name: " Ujjain " , state:20 } ,
    { id: 329 , name: " Umaria " , state:20 } ,
    { id: 355 , name: " Vidisha " , state:20 } ,
    { id: 796 , name: " Agatti Island " , state:19 } ,
    { id: 311 , name: " Lakshadweep " , state:19 } ,
    { id: 309 , name: " Kargil " , state:18 } ,
    { id: 310 , name: " Leh " , state:18 } ,
    { id: 301 , name: " Alappuzha " , state:17 } ,
    { id: 307 , name: " Ernakulam " , state:17 } ,
    { id: 306 , name: " Idukki " , state:17 } ,
    { id: 297 , name: " Kannur " , state:17 } ,
    { id: 295 , name: " Kasaragod " , state:17 } ,
    { id: 298 , name: " Kollam " , state:17 } ,
    { id: 304 , name: " Kottayam " , state:17 } ,
    { id: 305 , name: " Kozhikode " , state:17 } ,
    { id: 302 , name: " Malappuram " , state:17 } ,
    { id: 308 , name: " Palakkad " , state:17 } ,
    { id: 300 , name: " Pathanamthitta " , state:17 } ,
    { id: 296 , name: " Thiruvananthapuram " , state:17 } ,
    { id: 303 , name: " Thrissur " , state:17 } ,
    { id: 299 , name: " Wayanad " , state:17 } ,
    { id: 704 , name: " Almora " , state:35 } ,
    { id: 707 , name: " Bageshwar " , state:35 } ,
    { id: 699 , name: " Chamoli " , state:35 } ,
    { id: 708 , name: " Champawat " , state:35 } ,
    { id: 697 , name: " Dehradun " , state:35 } ,
    { id: 702 , name: " Haridwar " , state:35 } ,
    { id: 709 , name: " Nainital " , state:35 } ,
    { id: 698 , name: " Pauri Garhwal " , state:35 } ,
    { id: 706 , name: " Pithoragarh " , state:35 } ,
    { id: 700 , name: " Rudraprayag " , state:35 } ,
    { id: 701 , name: " Tehri Garhwal " , state:35 } ,
    { id: 705 , name: " Udham Singh Nagar " , state:35 } ,
    { id: 703 , name: " Uttarkashi " , state:35 } ,    
    { id: 710 , name: " Alipurduar District " , state:36 } ,
    { id: 711 , name: " Bankura " , state:36 } ,
    { id: 712 , name: " Basirhat HD (North 24 Parganas) " , state:36 } ,
    { id: 713 , name: " Birbhum " , state:36 } ,
    { id: 714 , name: " Bishnupur HD (Bankura) " , state:36 } ,
    { id: 715 , name: " Cooch Behar " , state:36 } ,
    { id: 783 , name: " COOCHBEHAR " , state:36 } ,
    { id: 716 , name: " Dakshin Dinajpur " , state:36 } ,
    { id: 717 , name: " Darjeeling " , state:36 } ,
    { id: 718 , name: " Diamond Harbor HD (S 24 Parganas) " , state:36 } ,
    { id: 719 , name: " East Bardhaman " , state:36 } ,
    { id: 720 , name: " Hoogly " , state:36 } ,
    { id: 721 , name: " Howrah " , state:36 } ,
    { id: 722 , name: " Jalpaiguri " , state:36 } ,
    { id: 723 , name: " Jhargram " , state:36 } ,
    { id: 724 , name: " Kalimpong " , state:36 } ,
    { id: 725 , name: " Kolkata " , state:36 } ,
    { id: 726 , name: " Malda " , state:36 } ,
    { id: 727 , name: " Murshidabad " , state:36 } ,
    { id: 728 , name: " Nadia " , state:36 } ,
    { id: 729 , name: " Nandigram HD (East Medinipore) " , state:36 } ,
    { id: 730 , name: " North 24 Parganas " , state:36 } ,
    { id: 731 , name: " Paschim Medinipore " , state:36 } ,
    { id: 732 , name: " Purba Medinipore " , state:36 } ,
    { id: 733 , name: " Purulia " , state:36 } ,
    { id: 734 , name: " Rampurhat HD (Birbhum) " , state:36 } ,
    { id: 735 , name: " South 24 Parganas " , state:36 } ,
    { id: 736 , name: " Uttar Dinajpur " , state:36 } ,
    { id: 737 , name: " West Bardhaman " , state:36 } ,
    { id: 138 , name: " Daman " , state:37 } ,
    { id: 139 , name: " Diu " , state:37 } ,
];
selectedState : any = "";
selectedCity : any = "";
dropdownCity: any = [];

populateCity(e : Event, value) {
  this.dropdownCity = this.City.filter(i => i.state == value);
  this.onBlurOrChange(e);
}
}