import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormBuilder, FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  
form: FormGroup;

  fname: FormControl = new FormControl("", [Validators.required,Validators.pattern('[a-zA-Z ]*')]);
  lname: FormControl = new FormControl("", [Validators.required,Validators.pattern('[a-zA-Z ]*')]);
  email: FormControl = new FormControl("", [Validators.required, Validators.email]);
  contact: FormControl = new FormControl("", [Validators.required,Validators.pattern("^[0-9_-]{10,12}")]);

  isLoading: boolean = false; // disable the submit button if loading
  success: boolean = false; // message sent successfully

  modal : Boolean = false; // display a modal after submission

  constructor(private formbuilder: FormBuilder, private http: HttpClient) {
    this.form = this.formbuilder.group({
      fname : this.fname,
      email : this.email,
      lname : this.lname,
      contact : this.contact
    });
  }


  ngOnInit(): void {
  }



  onBlur(e : Event) {
    let el : Element = e.target as Element;
    let invalid : Boolean;

    switch(el.getAttribute('name')) {
      case 'fname':
        invalid = this.fname.invalid; 
        break;
      case 'lname':
        invalid = this.fname.invalid; 
        break;
      case 'email':
        invalid = this.email.invalid; 
        break;
      case 'contact':
        invalid = this.contact.invalid;
        break;
      
    }

    el.className = invalid ? 'error' : '';
  }



  onSubmit() {
    if (this.form.status == "VALID") {
      this.form.disable(); // disable the form if it's valid to disable multiple submissions
      var formData: any = new FormData();
      formData.append("fname", this.form.get("fname").value);
      formData.append("lname", this.form.get("lname").value);
      formData.append("email", this.form.get("email").value);
      formData.append("contact", this.form.get("contact").value);
      this.isLoading = true; // sending the post request async so it's in progress
      this.modal = false; // hide the modal on multiple submits
      this.http.post("https://script.google.com/macros/s/AKfycbw5uBkchmmcoD4jH-1o0OqjOEFwsKUp186PFKLnitzPfJ2dDZvE/exec", formData).subscribe(
        (response) => {
          // choose the response message
          if (response["result"] == "success") {
            this.success = true;
          } else {
            this.success = false;
          }
          this.form.enable(); // re enable the form after a success
          this.modal = true; // show the response message
          this.isLoading = false; // re enable the submit button
          console.log(response);
        },
        (error) => {
          this.success = false;
          this.form.enable(); // re enable the form after a success
          this.modal = true; // show the response message
          this.isLoading = false; // re enable the submit button
          console.log(error);
        }
      );
    }
  }

// SELECT STATE AND CITY
State: any = [
  { id: 1, name: "AndraPradesh" },
  { id: 2, name: "ArunachalPradesh"},
  { id: 3, name: "Assam"},
  {id:4,name:"Bihar" },
  {id:5,name:"Chhattisgarh " },
  {id:6,name:"Goa" },
  {id:7,name:"Gujarat" },
  {id:8,name:"Haryana" },
  {id:9,name:"HimachalPradesh" },
  {id:10,name:" JammuKashmir" },
  {id:11,name:"Jharkhand" },
  {id:12,name:"Karnataka " },
  {id:13,name:"Kerala" },
  {id:14,name:"MadhyaPradesh" },
  {id:15,name:"Maharashtra" },
  {id:16,name:"Manipur" },
  {id:17,name:"Meghalaya" },
  {id:18,name:"Mizoram" },
  {id:19,name:"Nagaland" },
  {id:20,name:"Odisha" },
  {id:21,name:"Punjab" },
  {id:22,name:"Rajasthan" },
  {id:23,name:"sikkim"},
  {id:24,name:"TamilNadu" },
  {id:25,name:"Telangana" },
  {id:26,name:" Tripura" },
  {id:27,name:"UttarPradesh" },
  {id:28,name:"Uttarakhand" },
  {id:29,name:" WestBengal" },
  {id:30,name:" AndamanNicobar " },
  {id:31,name:" Chandigarh  " },
  {id:32,name:" DadraHaveli " },
  {id:33,name:"  DamanDiu " },
  {id:34,name:" Delhi " },
  {id:35,name:" Lakshadweep " },
  {id:36,name:" Puducherry" },

]

City: any = [
  { id: 1, name: "Anantapur", state: 1 },
  { id: 2, name: "Chittoor", state: 1 },
  { id: 3, name: "East Godavari", state: 1 },
  { id: 4, name: "Guntur", state: 1 },
  { id: 5, name: "Kadapa", state: 1 },
  { id: 6, name: "Krishna", state: 1 },
  { id: 7, name: "Kurnool", state: 1 },
  { id: 8, name: "Prakasam", state: 1 },
  { id: 9, name: "Nellore", state: 1 },
  { id: 10, name: "Srikakulam", state: 1 },
  { id: 11, name: "Visakhapatnam", state: 1 },
  { id: 12, name: "Vizianagaram", state: 1 },
  { id: 13, name: "West Godavari", state: 1 },
  { id: 1, name:  "Anjaw", state: 2 },
  { id: 2, name: "Changlang", state: 2 },
  { id: 3, name:  "Dibang Valley", state: 2 },
  { id: 4, name: "East Kameng", state: 2 },
  { id: 5, name:  "East Siang", state: 2 },
  { id: 6, name:  "Kra Daadi", state: 2 },
  { id: 7, name: "Kurung Kumey", state: 2 },
  { id: 8, name:  "Lohit", state: 2 },
  { id: 9, name:  "Longding", state: 2 },
  { id: 10, name: "Lower Dibang Valley", state: 2 },
  { id: 11, name:  "Lower Subansiri", state: 2 },
  { id: 12, name:  "Namsai", state: 2 },
  { id: 13, name:  "Papum Pare", state: 2 },
  { id: 14, name:  "Siang", state: 2 },
  { id: 15, name:  "Tawang", state: 2 },
  { id: 16, name:  "Tirap", state: 2 },
  { id: 17, name: "Upper Siang", state: 2 },
  { id: 18, name:  "Upper Subansiri", state: 2 },
  { id: 19, name: "West Kameng", state: 2 },
  { id: 20, name:  "West Kameng", state: 2 },
  { id: 21, name:  "West Siang", state: 2 },
  { id: 22, name:  "Itanagar", state: 2 },
  { id: 1, name: "Baksa", state: 3 },
  { id: 2, name: "Barpeta", state: 3 },
  { id: 3, name: "Biswanath", state: 3 },
  { id: 4, name: "Bongaigaon", state: 3 },
  { id:5 , name: "Cachar", state: 3 },
  { id:6, name: "Charaideo", state: 3 },
  { id:7 , name: "Chirang", state: 3 },
  { id:8 , name: "Darrang", state: 3 },
  { id:9 , name: "Dhemaji", state: 3 },
  { id:10 , name: "Dhubri", state: 3 },
  { id:11 , name: "Dibrugarh", state: 3 },
  { id:12 , name: "Goalpara", state: 3 },
  { id: 13, name: "Golaghat", state: 3 },
  { id: 14, name: "Hailakandi", state: 3 },
  { id: 15, name: "Hojai", state: 3 },
  { id:16 , name: "Jorhat", state: 3 },
  { id:17 , name: "Kamrup Metropolitan", state: 3 },
  { id:18 , name: "Kamrup (Rural)", state: 3 },
  { id:19 , name: "Karbi", state: 3 },
  { id:20 , name: "Anglong", state: 3 },
  { id:21 , name: "Karimganj", state: 3 },
  { id:22 , name: "Kokrajhar", state: 3 },
  { id:23 , name: "Lakhimpur", state: 3 },
  { id:24 , name: "Majuli", state: 3 },
  { id:25 , name: "Morigaon", state: 3 },
  { id:26 , name: "Nagaon", state: 3 },
  { id:27 , name: "Nalbari", state: 3 },
  { id:28 , name: "Dima Hasao", state: 3 },
  { id:29 , name: "Sivasagar", state: 3 },
  { id:30 , name: "Sonitpur", state: 3 },
  { id:31 , name: "South Salmara Mankachar", state: 3 },
  { id:32 , name: "Tinsukia", state: 3 },
  { id:33 , name: "Udalguri", state: 3 },
  { id:34 , name: "West Karbi Anglong", state: 3 },
  { id: 1, name: "Araria", state: 4 },
  { id: 2, name: "Arwal", state: 4 },
  { id: 3, name: "Aurangabad", state: 4 },
  { id: 4, name: "Banka", state: 4 },
  { id:5 , name: "Begusarai", state: 4 },
  { id:6, name: "Bhagalpur", state: 4 },
  { id:7 , name: "Bhojpur", state: 4 },
  { id:8 , name: "Buxar", state: 4 },
  { id:9 , name: "Darbhanga", state: 4 },
  { id:10 , name: "East Champaran", state: 4 },
  { id:11 , name: "Gaya", state: 4 },
  { id:12 , name: "Gopalganj", state: 4 },
  { id: 13, name: "Jamui", state: 4 },
  { id: 14, name: "Jehanabad", state: 4 },
  { id: 15, name: "Kaimur", state: 4 },
  { id:16 , name: "Katihar", state: 4 },
  { id:17 , name: "Khagaria", state: 4 },
  { id:18 , name: "Kishanganj", state: 4 },
  { id:19 , name: "Lakhisarai", state: 4 },
  { id:20 , name: "Madhepura", state: 4 },
  { id:21 , name: "Madhubani", state: 4 },
  { id:22 , name: "Munger", state: 4 },
  { id:23 , name: "Muzaffarpur", state: 4 },
  { id:24 , name: "Nalanda", state: 4},
  { id:25 , name: "Nawada", state: 4 },
  { id:26 , name: "Patna", state: 4 },
  { id:27 , name: "Purnia", state: 4 },
  { id:28 , name: "Rohtas", state: 4 },
  { id:29 , name: "Saharsa", state: 4 },
  { id:30 , name: "Samastipur", state: 4 },
  { id:31 , name: "Saran", state: 4 },
  { id:32 , name: "Sheikhpura", state: 4 },
  { id:33 , name: "Sheohar", state: 4 },
  { id:34 , name: "Sitamarhi", state: 4},
  { id:35 , name: "Siwan", state: 4},
  { id:36 , name: "Supaul", state: 4},
  { id:37 , name: "Vaishali", state: 4},
  { id:38 , name: "West Champaran", state: 4},
  { id: 1, name:  "Karaikal", state: 36},
  { id: 2, name:  "Mahe", state: 36},
  { id: 3, name:  "Puducherry", state: 36},
  { id: 4, name:  "Yanam", state: 36},
  { id: 1, name:  "Central Delhi", state: 35},
  { id: 2, name:  "East Delhi", state: 34},
  { id: 3, name:  "New Delhi", state: 34},
  { id: 4, name:  "North Delhi", state: 34},
  { id: 5, name:  "North East Delhi", state: 34},
  { id: 6, name:  "North West Delhi", state: 34},
  { id: 7, name:  "Shahdara", state: 34},
  { id: 8, name: "South Delhi", state: 34},
  { id: 9, name: "South East Delhi", state: 34},
  { id: 10, name: "South West Delhi", state: 34},
  { id: 11, name:"West Delhi", state: 34},
  { id: 1, name:"Daman", state: 33},
  { id: 2, name:"Diu", state: 33},
  { id: 1, name:"Dadra Nagar Haveli", state: 32},
  { id: 1, name:"Chandigarh", state: 31},
  { id: 1, name:"Nicobar", state: 30},
  { id: 2, name:"North Middle Andaman", state: 30},
  { id: 3, name:"South Andaman", state: 30},
  { id: 1, name:"Alipurduar", state: 29},
  { id: 2, name:"Bankura", state: 29},
  { id: 3, name:"Birbhum", state: 29},
  { id: 4, name:"Cooch Behar", state: 29},
  { id: 5, name:"Dakshin Dinajpur", state: 29},
  { id: 6, name:"Darjeeling", state:29},
  { id: 7, name:"Hooghly", state: 29},
  { id: 8, name:"Howrah", state: 29},
  { id: 9, name:"Jalpaiguri", state: 29},
  { id: 10, name:"Jhargram", state: 29},
  { id: 11, name:"Kalimpong", state: 29},
  { id: 12, name:"Kolkata", state: 29},
  { id: 13, name:"Malda", state: 29},
  { id: 14, name:"Murshidabad", state: 29},
  { id: 15, name:"Nadia", state: 29},
  { id: 16, name:"North 24 Parganas", state: 29},
  { id: 17, name:"Paschim Bardhaman", state: 29},
  { id: 18, name:"Paschim Medinipur", state: 29},
  { id: 19, name:"Purba Bardhaman", state: 29},
  { id: 20, name:"Purba Medinipur", state: 29},
  { id: 21, name:"Purulia", state: 29},
  { id: 22, name:"South 24 Parganas", state: 29},
  { id: 23, name:"Uttar Dinajpur", state: 29},
  { id: 1, name:"Almora", state: 28},
  { id: 2, name:"Bageshwar", state: 28},
  { id: 3, name:"Chamoli", state: 28},
  { id: 4, name:"Champawat", state: 28},
  { id: 5, name:"Dehradun", state: 28},
  { id: 6, name:"Haridwar", state: 28},
  { id: 7, name:"Nainital", state: 28},
  { id: 8, name:"Pauri", state: 28},
  { id: 9, name:"Pithoragarh", state: 28},
  { id: 10, name:"Rudraprayag", state: 28},
  { id: 11, name:"Tehri", state: 28},
  { id: 12, name:"Udham Singh Nagar", state: 28},
  { id: 13, name:"Uttarkashi", state: 28},
  { id: 1, name: "Ahmednagar", state: 15 },
  { id: 2, name: "Akola", state: 15 },
  { id: 3, name: "Amravati", state: 15 },
  { id: 4, name: "Aurangabad", state: 15 },
  { id: 5, name: "Beed", state: 15 },
  { id: 6, name: "Bhandara", state: 15 },
  { id: 7, name: "Buldhana", state: 15 },
  { id: 8, name: "Chandrapur", state: 15 },
  { id: 9, name: "Dhule", state: 15 },
  { id: 10, name: "Gadchiroli", state: 15 },
  { id: 11, name: "Gondia", state: 15 },
  { id: 12, name: "Hingoli", state: 15 },
  { id: 13, name: "Jalgaon", state: 15 },
  { id: 14, name: "Jalna", state: 15 },
  { id: 15, name: "Kolhapur", state: 15 },
  { id: 16, name: "Latur", state: 15 },
  { id: 17, name: "Mumbai City", state: 15 },
  { id: 18, name: "Mumbai Suburban", state: 15 },
  { id: 19, name: "Nagpur", state: 15 },
  { id: 20, name: "Nanded", state: 15 },
  { id: 21, name: "Nandurbar", state: 15 },
  { id: 22, name: "Nashik", state: 15 },
  { id: 23, name: "Osmanabad", state: 15 },
  { id: 24, name: "Palghar", state: 15 },
  { id: 25, name: "Parbhani", state: 15 },
  { id: 26, name: "Pune", state: 15 },
  { id: 27, name: "Raigad", state: 15 },
  { id: 28, name: "Ratnagiri", state: 15 },
  { id: 29, name: "Sangli", state: 15 },
  { id: 30, name: "Satara", state: 15 },
  { id: 31, name: "Sindhudurg", state: 15 },
  { id: 32, name: "Solapur", state: 15 },
  { id: 33, name: "Thane", state: 15 },
  { id: 34, name: "Wardha", state: 15 },
  { id: 35, name: "Washim", state: 15 },
  { id: 36, name: "Yavatmal", state: 15 },
  { id: 1, name: "Bishnupur", state: 16 },
  { id: 2, name: "Chandel", state: 16 },
  { id: 3, name: "Churachandpur", state: 16 },
  { id: 4, name: "Imphal East", state: 16 },
  { id: 5, name: "Imphal West", state: 16 },
  { id: 6, name: "Jiribam", state: 16 },
  { id: 7, name: "Kakching", state: 16 },
  { id: 8, name: "Kamjong", state: 16 },
  { id: 9, name: "Kangpokpi", state: 16 },
  { id: 10, name: "Noney", state: 16 },
  { id: 11, name: "Pherzawl", state: 16 },
  { id: 12, name: "Senapati", state: 16 },
  { id: 13, name: "Tamenglong", state: 16 },
  { id: 14, name: "Tengnoupal", state: 16 },
  { id: 15, name: "Thoubal", state: 16 },
  { id: 16, name: "Ukhrul", state: 16 },
  { id: 1, name: "East Garo Hills", state: 17 },
  { id: 2, name: "East Jaintia Hills", state: 17 },
  { id: 3, name: "East Khasi Hills", state: 17 },
  { id: 4, name: "North Garo Hills", state: 17 },
  { id: 5, name: "Ri Bhoi", state: 17 },
  { id: 6, name: "South Garo Hills", state: 17 },
  { id: 7, name: "South West Garo Hills", state: 17 },
  { id: 8, name: "South West Khasi Hills", state: 17 },
  { id: 9, name: "West Garo Hills", state: 17 },
  { id: 10, name: "West Jaintia Hills", state: 17 },
  { id: 11, name: "West Khasi Hills", state: 17 },
  { id: 1, name: "Aizawl", state: 18 },
  { id: 2, name: "Champhai", state: 18 },
  { id: 3, name: "Kolasib", state: 18 },
  { id: 4, name: "Lawngtlai", state: 18 },
  { id: 5, name: "Lunglei", state: 18 },
  { id: 6, name: "Mamit", state: 18 },
  { id: 7, name: "Saiha", state: 18 },
  { id: 8, name: "Serchhip", state: 18 },
  { id: 9, name: "Aizawl", state: 18 },
  { id: 10, name: "Champhai", state: 18 },
  { id: 11, name: "Kolasib", state: 18 },
  { id: 12, name: "Lawngtlai", state: 18 },
  { id: 13, name: "Lunglei", state: 18 },
  { id: 14, name: "Mamit", state: 18 },
  { id: 15, name: "Saiha", state: 18 },
  { id: 16, name: "Serchhip", state: 18 },
  { id: 1, name: "Dimapur", state: 19 },
  { id: 2, name: "Kiphire", state: 19 },
  { id: 3, name: "Kohima", state: 19 },
  { id: 4, name: "Longleng", state: 19 },
  { id: 5, name: "Mokokchung", state: 19 },
  { id: 6, name: "Mon", state: 19 },
  { id: 7, name: "Peren", state: 19 },
  { id: 8, name: "Phek", state: 19 },
  { id: 9, name: "Tuensang", state: 19 },
  { id: 10, name: "Wokha", state: 19 },
  { id: 11, name: "Zunheboto", state: 19 },
  { id: 1, name: "Angul", state: 20 },
  { id: 2, name: "Balangir", state: 20 },
  { id: 3, name: "Balasore", state: 20 },
  { id: 4, name: "Bargarh", state: 20 },
  { id: 5, name: "Bhadrak", state: 20 },
  { id: 6, name: "Boudh", state: 20 },
  { id: 7, name: "Cuttack", state: 20 },
  { id: 8, name: "Debagarh", state: 20 },
  { id: 9, name: "Dhenkanal", state: 20 },
  { id: 10, name: "Gajapati", state: 20 },
  { id: 11, name: "Ganjam", state: 20 },
  { id: 12, name: "Jagatsinghpur", state: 20 },
  { id: 13, name: "Jajpur", state: 20 },
  { id: 14, name: "Jharsuguda", state: 20 },
  { id: 15, name: "Kalahandi", state: 20 },
  { id: 16, name: "Kandhamal", state: 20 },
  { id: 17, name: "Kendrapara", state: 20 },
  { id: 18, name: "Kendujhar", state: 20 },
  { id: 19, name: "Khordha", state: 20 },
  { id: 20, name: "Koraput", state: 20 },
  { id: 21, name: "Malkangiri", state: 20 },
  { id: 22, name: "Mayurbhanj", state: 20 },
  { id: 23, name: "Nabarangpur", state: 20 },
  { id: 24, name: "Nayagarh", state: 20 },
  { id: 25, name: "Nuapada", state: 20 },
  { id: 26, name: "Puri", state: 20 },
  { id: 27, name: "Rayagada", state: 20 },
  { id: 28, name: "Sambalpur", state: 20 },
  { id: 29, name: "Subarnapur", state: 20 },
  { id: 30, name: "Sundergarh", state: 20 },
  { id: 1, name: "Amritsar", state: 21 },
  { id: 2, name: "Barnala", state: 21 },
  { id: 3, name: "Bathinda", state: 21 },
  { id: 4, name: "Faridkot", state: 21 },
  { id: 5, name: "Fatehgarh Sahib", state: 21 },
  { id: 6, name: "Fazilka", state: 21 },
  { id: 7, name: "Firozpur", state: 21 },
  { id: 8, name: "Gurdaspur", state: 21 },
  { id: 9, name: "Hoshiarpur", state: 21 },
  { id: 10, name: "Jalandhar", state: 21 },
  { id: 11, name: "Kapurthala", state: 21 },
  { id: 12, name: "Ludhiana", state: 21 },
  { id: 13, name: "Mansa", state: 21 },
  { id: 14, name: "Moga", state: 21 },
  { id: 15, name: "Mohali", state: 21 },
  { id: 16, name: "Muktsar", state: 21 },
  { id: 17, name: "Pathankot", state: 21 },
  { id: 18, name: "Patiala", state: 21 },
  { id: 19, name: "Rupnagar", state: 21 },
  { id: 20, name: "Sangrur", state: 21 },
  { id: 21, name: "Shaheed Bhagat Singh Nagar", state: 21 },
  { id: 22, name: "Tarn Taran", state: 21 },
  { id: 1, name: "Ajmer", state: 22 },
  { id: 2, name: "Alwar", state: 22 },
  { id: 3, name: "Banswara", state: 22 },
  { id: 4, name: "Baran", state: 22 },
  { id: 5, name: "Barmer", state: 22 },
  { id: 6, name: "Bharatpur", state: 22 },
  { id: 7, name: "Bhilwara", state: 22 },
  { id: 8, name: "Bikaner", state: 22 },
  { id: 9, name: "Bundi", state: 22 },
  { id: 10, name: "Chittorgarh", state: 22 },
  { id: 11, name: "Churu", state: 22 },
  { id: 12, name: "Dausa", state: 22 },
  { id: 13, name: "Dholpur", state: 22 },
  { id: 14, name: "Dungarpur", state: 22 },
  { id: 15, name: "Ganganagar", state: 22 },
  { id: 16, name: "Hanumangarh", state: 22 },
  { id: 17, name: "Jaipur", state: 22 },
  { id: 18, name: "Jaisalmer", state: 22 },
  { id: 19, name: "Jalore", state: 22 },
  { id: 20, name: "Jhalawar", state: 22 },
  { id: 21, name: "Jhunjhunu", state: 22 },
  { id: 22, name: "Jodhpur", state: 22 },
  { id: 23, name: "Karauli", state: 22 },
  { id: 24, name: "Kota", state: 22 },
  { id: 25, name: "Nagaur", state: 22 },
  { id: 26, name: "Pali", state: 22 },
  { id: 27, name: "Pratapgarh", state: 22 },
  { id: 28, name: "Rajsamand", state: 22 },
  { id: 29, name: "Sawai Madhopur", state: 22 },
  { id: 30, name: "Sikar", state: 22 },
  { id: 31, name: "Sirohi", state: 22 },
  { id: 32, name: "Tonk", state: 22 },
  { id: 33, name: "Udaipur", state: 22 },
  { id: 1, name: "East Sikkim", state: 23 },
  { id: 2, name: "North Sikkim", state: 23 },
  { id: 3, name: "South Sikkim", state: 23 },
  { id: 4, name: "West Sikkim", state: 23 },
  { id: 1, name: "Ariyalur", state: 24 },
  { id: 2, name: "Chennai", state: 24 },
  { id: 3, name: "Coimbatore", state: 24 },
  { id: 4, name: "Cuddalore", state: 24 },
  { id: 5, name: "Dharmapuri", state: 24 },
  { id: 6, name: "Dindigul", state: 24 },
  { id: 7, name: "Erode", state: 24 },
  { id: 8, name: "Kanchipuram", state: 24 },
  { id: 9, name: "Kanyakumari", state: 24 },
  { id: 10, name: "Karur", state: 24 },
  { id: 11, name: "Krishnagiri", state: 24 },
  { id: 12, name: "Madurai", state: 24 },
  { id: 13, name: "Nagapattinam", state: 24 },
  { id: 14, name: "Namakkal", state: 24 },
  { id: 15, name: "Nilgiris", state: 24 },
  { id: 16, name: "Perambalur", state: 24 },
  { id: 17, name: "Pudukkottai", state: 24 },
  { id: 18, name: "Ramanathapuram", state: 24 },
  { id: 19, name: "Salem", state: 24 },
  { id: 20, name: "Sivaganga", state: 24 },
  { id: 21, name: "Thanjavur", state: 24 },
  { id: 22, name: "Theni", state: 24 },
  { id: 23, name: "Thoothukudi", state: 24 },
  { id: 24, name: "Tiruchirappalli", state: 24 },
  { id: 25, name: "Tirunelveli", state: 24 },
  { id: 26, name: "Tiruppur", state: 24 },
  { id: 27, name: "Tiruvallur", state: 24 },
  { id: 28, name: "Tiruvannamalai", state: 24 },
  { id: 29, name: "Tiruvarur", state: 24 },
  { id: 30, name: "Vellore", state: 24 },
  { id: 31, name: "Viluppuram", state: 24 },
  { id: 32, name: "Virudhunagar", state: 24 },
  { id: 1, name: "Adilabad", state: 25 },
  { id: 2, name: "Bhadradri Kothagudem", state: 25 },
  { id: 3, name: "Hyderabad", state: 25 },
  { id: 4, name: "Jagtial", state: 25 },
  { id: 5, name: "Jangaon", state: 25 },
  { id: 6, name: "Jayashankar", state: 25 },
  { id: 7, name: "Jogulamba", state: 25 },
  { id: 8, name: "Kamareddy", state: 25 },
  { id: 9, name: "Karimnagar", state: 25 },
  { id: 10, name: "Khammam", state: 25 },
  { id: 11, name: "Komaram Bheem", state: 25 },
  { id: 12, name: "Mahabubabad", state: 25 },
  { id: 13, name: "Mahbubnagar", state: 25 },
  { id: 14, name: "Mancherial", state: 25 },
  { id: 15, name: "Medak", state: 25 },
  { id: 16, name: "Medchal", state: 25 },
  { id: 17, name: "Nagarkurnool", state: 25 },
  { id: 18, name: "Nalgonda", state: 25 },
  { id: 19, name: "Nirmal", state: 25 },
  { id: 20, name: "Nizamabad", state: 25 },
  { id: 21, name: "Peddapalli", state: 25 },
  { id: 22, name: "Rajanna Sircilla", state: 25 },
  { id: 23, name: "Ranga Reddy", state: 25 },
  { id: 24, name: "Sangareddy", state: 25 },
  { id: 25, name: "Siddipet", state: 25 },
  { id: 26, name: "Suryapet", state: 25 },
  { id: 27, name: "Vikarabad", state: 25 },
  { id: 28, name: "Wanaparthy", state: 25 },
  { id: 29, name: "Warangal Rural", state: 25 },
  { id: 30, name: "Warangal Urban", state: 25 },
  { id: 31, name: "Yadadri Bhuvanagiri", state: 25 },
  { id: 1, name: "Dhalai", state: 26 },
  { id: 2, name: "Gomati", state: 26 },
  { id: 3, name: "Khowai", state: 26 },
  { id: 4, name: "North Tripura", state: 26 },
  { id: 5, name: "Sepahijala", state: 26 },
  { id: 6, name: "South Tripura", state: 26 },
  { id: 7, name: "Unakoti", state: 26 },
  { id: 8, name: "West Tripura", state: 26 },
  { id: 1, name: "Balod", state: 5 },
  { id: 2, name: "Baloda Bazar", state: 5 },
  { id: 3, name: "Balrampur", state: 5 },
  { id: 4, name: "Bastar", state: 5 },
  { id: 5, name: "Bemetara", state: 5 },
  { id: 6, name: "Bijapur", state: 5 },
  { id: 7, name: "Bilaspur", state: 5 },
  { id: 8, name: "Dantewada", state: 5 },
  { id: 9, name: "Dhamtari", state: 5 },
  { id: 10, name: "Durg", state: 5 },
  { id: 11, name: "Gariaband", state: 5 },
  { id: 12, name: "Janjgir Champa", state: 5 },
  { id: 13, name: "Jashpur", state: 5 },
  { id: 14, name: "Kabirdham", state: 5 },
  { id: 15, name: "Kanker", state: 5 },
  { id: 16, name: "Kondagaon", state: 5 },
  { id: 17, name: "Korba", state: 5 },
  { id: 18, name: "Koriya", state: 5 },
  { id: 19, name: "Mahasamund", state: 5 },
  { id: 20, name: "Mungeli", state: 5 },
  { id: 21, name: "Narayanpur", state: 5 },
  { id: 22, name: "Raigarh", state: 5 },
  { id: 23, name: "Raipur", state: 5 },
  { id: 24, name: "Rajnandgaon", state: 5 },
  { id: 25, name: "Sukma", state: 5 },
  { id: 26, name: "Surajpur", state: 5 },
  { id: 27, name: "Surguja", state: 5 },
  { id: 1, name: "North Goa", state: 6 },
  { id: 2, name: "South Goa", state: 6 },
  { id: 1, name: "Agra", state: 27 },
  { id: 2, name: "Aligarh", state: 27 },
  { id: 3, name: "Allahabad", state: 27 },
  { id: 4, name: "Ambedkar Nagar", state: 27 },
  { id: 5, name: "Amethi", state: 27 },
  { id: 6, name: "Amroha", state: 27 },
  { id: 7, name: "Auraiya", state: 27 },
  { id: 8, name: "Azamgarh", state: 27 },
  { id: 9, name: "Baghpat", state: 27 },
  { id: 10, name: "Bahraich", state: 27 },
  { id: 11, name: "Ballia", state: 27 },
  { id: 12, name: "Balrampur", state: 27 },
  { id: 13, name: "Banda", state: 27 },
  { id: 14, name: "Barabanki", state: 27 },
  { id: 15, name: "Bareilly", state: 27 },
  { id: 16, name: "Basti", state: 27 },
  { id: 17, name: "Bhadohi", state: 27 },
  { id: 18, name: "Bijnor", state: 27 },
  { id: 19, name: "Budaun", state: 27 },
  { id: 20, name: "Bulandshahr", state: 27 },
  { id: 21, name: "Chandauli", state: 27 },
  { id: 22, name: "Chitrakoot", state: 27 },
  { id: 23, name: "Deoria", state: 27 },
  { id: 24, name: "Etah", state: 27 },
  { id: 25, name: "Etawah", state: 27 },
  { id: 26, name: "Faizabad", state: 27 },
  { id: 27, name: "Farrukhabad", state: 27 },
  { id: 28, name: "Fatehpur", state: 27 },
  { id: 29, name: "Firozabad", state: 27 },
  { id: 30, name: "Gautam Buddha Nagar", state: 27 },
  { id: 31, name: "Ghaziabad", state: 27 },
  { id: 32, name: "Ghazipur", state: 27 },
  { id: 33, name: "Gonda", state: 27 },
  { id: 34, name: "Gorakhpur", state: 27 },
  { id: 35, name: "Hamirpur", state: 27 },
  { id: 36, name: "Hapur", state: 27 },
  { id: 37, name: "Hardoi", state: 27 },
  { id: 38, name: "Hathras", state: 27 },
  { id: 39, name: "Jalaun", state: 27 },
  { id: 40, name: "Jaunpur", state: 27 },
  { id: 41, name: "Jhansi", state: 27 },
  { id: 42, name: "Kannauj", state: 27 },
  { id: 43, name: "Kanpur Dehat", state: 27 },
  { id: 44, name: "Kanpur Nagar", state: 27 },
  { id: 45, name: "Kasganj", state: 27 },
  { id: 46, name: "Kaushambi", state: 27 },
  { id: 47, name: "Kheri", state: 27 },
  { id: 48, name: "Kushinagar", state: 27 },
  { id: 49, name: "Lalitpur", state: 27 },
  { id: 50, name: "Lucknow", state: 27 },
  { id: 51, name: "Maharajganj", state: 27 },
  { id: 52, name: "Mahoba", state: 27 },
  { id: 53, name: "Mainpuri", state: 27 },
  { id: 54, name: "Mathura", state: 27 },
  { id: 55, name: "Mau", state: 27 },
  { id: 56, name: "Meerut", state: 27 },
  { id: 57, name: "Mirzapur", state: 27 },
  { id: 58, name: "Moradabad", state: 27 },
  { id: 59, name: "Muzaffarnagar", state: 27 },
  { id: 60, name: "Pilibhit", state: 27 },
  { id: 61, name: "Pratapgarh", state: 27 },
  { id: 62, name: "Raebareli", state: 27 },
  { id: 63, name: "Rampur", state: 27 },
  { id: 64, name: "Saharanpur", state: 27 },
  { id: 65, name: "Sambhal", state: 27 },
  { id: 66, name: "Sant Kabir Nagar", state: 27 },
  { id: 67, name: "Shahjahanpur", state: 27 },
  { id: 68, name: "Shamli", state: 27 },
  { id: 69, name: "Shravasti", state: 27 },
  { id: 70, name: "Siddharthnagar", state: 27 },
  { id: 71, name: "Sitapur", state: 27 },
  { id: 72, name: "Sonbhadra", state: 27 },
  { id: 73, name: "Sultanpur", state: 27 },
  { id: 74, name: "Unnao", state: 27 },
  { id: 75, name: "Varanasi", state: 27 },
  { id: 1, name: "Agar Malwa", state: 14 },
  { id: 2, name: "Alirajpur", state: 14 },
  { id: 3, name: "Anuppur", state: 14 },
  { id: 4, name: "Ashoknagar", state: 14 },
  { id: 5, name: "Balaghat", state: 14 },
  { id: 6, name: "Barwani", state: 14 },
  { id: 7, name: "Betul", state: 14 },
  { id: 8, name: "Bhind", state: 14 },
  { id: 9, name: "Bhopal", state: 14 },
  { id: 10, name: "Burhanpur", state: 14 },
  { id: 11, name: "Chhatarpur", state: 14 },
  { id: 12, name: "Chhindwara", state: 14 },
  { id: 13, name: "Damoh", state: 14 },
  { id: 14, name: "Datia", state: 14 },
  { id: 15, name: "Dewas", state: 14 },
  { id: 16, name: "Dhar", state: 14 },
  { id: 17, name: "Dindori", state: 14 },
  { id: 18, name: "Guna", state: 14 },
  { id: 19, name: "Gwalior", state: 14 },
  { id: 20, name: "Harda", state: 14 },
  { id: 21, name: "Hoshangabad", state: 14 },
  { id: 22, name: "Indore", state: 14 },
  { id: 23, name: "Jabalpur", state: 14 },
  { id: 24, name: "Jhabua", state: 14 },
  { id: 25, name: "Katni", state: 14 },
  { id: 26, name: "Khandwa", state: 14 },
  { id: 27, name: "Khargone", state: 14 },
  { id: 28, name: "Mandla", state: 14 },
  { id: 29, name: "Mandsaur", state: 14 },
  { id: 30, name: "Morena", state: 14 },
  { id: 31, name: "Narsinghpur", state: 14 },
  { id: 32, name: "Neemuch", state: 14 },
  { id: 33, name: "Panna", state: 14 },
  { id: 34, name: "Raisen", state: 14 },
  { id: 35, name: "Rajgarh", state: 14 },
  { id: 36, name: "Ratlam", state: 14 },
  { id: 37, name: "Rewa", state: 14 },
  { id: 38, name: "Sagar", state: 14 },
  { id: 39, name: "Satna", state: 14 },
  { id: 40, name: "Sehore", state: 14 },
  { id: 41, name: "Seoni", state: 14 },
  { id: 42, name: "Shahdol", state: 14 },
  { id: 43, name: "Shajapur", state: 14 },
  { id: 44, name: "Sheopur", state: 14 },
  { id: 45, name: "Shivpuri", state: 14 },
  { id: 46, name: "Sidhi", state: 14 },
  { id: 47, name: "Singrauli", state: 14 },
  { id: 48, name: "Tikamgarh", state: 14 },
  { id: 49, name: "Ujjain", state: 14 },
  { id: 50, name: "Umaria", state: 14 },
  { id: 51, name: "Vidisha", state: 14 },
  { id: 1, name: "Alappuzha", state: 13 },
  { id: 2, name: "Ernakulam", state: 13 },
  { id: 3, name: "Idukki", state: 13 },
  { id: 4, name: "Kannur", state: 13 },
  { id: 5, name: "Kasaragod", state: 13 },
  { id: 6, name: "Kollam", state: 13 },
  { id: 7, name: "Kottayam", state: 13 },
  { id: 8, name: "Kozhikode", state: 13 },
  { id: 9, name: "Malappuram", state: 13 },
  { id: 10, name: "Palakkad", state: 13 },
  { id: 11, name: "Pathanamthitta", state: 13 },
  { id: 12, name: "Thiruvananthapuram", state: 13 },
  { id: 13, name: "Thrissur", state: 13 },
  { id: 14, name: "Wayanad", state: 13 },
  { id: 1, name: "Bagalkot", state: 12 },
  { id: 2, name: "Bangalore Rural", state: 12 },
  { id: 3, name: "Bangalore Urban", state: 12 },
  { id: 4, name: "Belgaum", state: 12 },
  { id: 5, name: "Bellary", state: 12 },
  { id: 6, name: "Bidar", state: 12 },
  { id: 7, name: "Vijayapura", state: 12 },
  { id: 8, name: "Chamarajanagar", state: 12 },
  { id: 9, name: "Chikkaballapur", state: 12 },
  { id: 10, name: "Chikkamagaluru", state: 12 },
  { id: 11, name: "Chitradurga", state: 12 },
  { id: 12, name: "Dakshina Kannada", state: 12 },
  { id: 13, name: "Davanagere", state: 12 },
  { id: 14, name: "Dharwad", state: 12 },
  { id: 15, name: "Gadag", state: 12 },
  { id: 16, name: "Gulbarga", state: 12 },
  { id: 17, name: "Hassan", state: 12 },
  { id: 18, name: "Haveri", state: 12 },
  { id: 19, name: "Kodagu", state: 12 },
  { id: 20, name: "Kolar", state: 12 },
  { id: 21, name: "Koppal", state: 12 },
  { id: 22, name: "Mandya", state: 12 },
  { id: 23, name: "Mysore", state: 12 },
  { id: 24, name: "Raichur", state: 12 },
  { id: 25, name: "Ramanagara", state: 12 },
  { id: 26, name: "Shimoga", state: 12 },
  { id: 27, name: "Tumkur", state: 12 },
  { id: 28, name: "Udupi", state: 12 },
  { id: 29, name: "Uttara Kannada", state: 12 },
  { id: 30, name: "Yadgir", state: 12 },
  { id: 1, name: "Ahmedabad", state: 7 },
  { id: 2, name: "Amreli", state: 7 },
  { id: 3, name: "Anand", state: 7 },
  { id: 4, name: "Aravalli", state: 7 },
  { id: 5, name: "Banaskantha", state: 7 },
  { id: 6, name: "Bharuch", state: 7 },
  { id: 7, name: "Bhavnagar", state: 7 },
  { id: 8, name: "Botad", state: 7 },
  { id: 9, name: "Chhota Udaipur", state: 7 },
  { id: 10, name: "Dahod", state: 7 },
  { id: 11, name: "Dang", state: 7 },
  { id: 12, name: "Devbhoomi Dwarka", state: 7 },
  { id: 13, name: "Gandhinagar", state: 7 },
  { id: 14, name: "Gir Somnath", state: 7 },
  { id: 15, name: "Jamnagar", state: 7 },
  { id: 16, name: "Junagadh", state: 7 },
  { id: 17, name: "Kheda", state: 7 },
  { id: 18, name: "Kutch", state: 7 },
  { id: 19, name: "Mahisagar", state: 7 },
  { id: 20, name: "Mehsana", state: 7 },
  { id: 21, name: "Morbi", state: 7 },
  { id: 22, name: "Narmada", state: 7 },
  { id: 23, name: "Navsari", state: 7 },
  { id: 24, name: "Panchmahal", state: 7 },
  { id: 25, name: "Patan", state: 7 },
  { id: 26, name: "Porbandar", state: 7 },
  { id: 27, name: "Rajkot", state: 7 },
  { id: 28, name: "Sabarkantha", state: 7 },
  { id: 29, name: "Surat", state: 7 },
  { id: 30, name: "Surendranagar", state: 7 },
  { id: 31, name: "Tapi", state: 7 },
  { id: 32, name: "Vadodara", state: 7 },
  { id: 33, name: "Valsad", state: 7 },
  { id: 1, name: "Ambala", state: 8 },
  { id: 2, name: "Bhiwani", state: 8 },
  { id: 3, name: "Charkhi Dadri", state: 8 },
  { id: 4, name: "Faridabad", state: 8 },
  { id: 5, name: "Fatehabad", state: 8 },
  { id: 6, name: "Gurugram", state: 8 },
  { id: 7, name: "Hisar", state: 8 },
  { id: 8, name: "Jhajjar", state: 8 },
  { id: 9, name: "Jind", state: 8 },
  { id: 10, name: "Kaithal", state: 8 },
  { id: 11, name: "Karnal", state: 8 },
  { id: 12, name: "Kurukshetra", state: 8 },
  { id: 13, name: "Mahendragarh", state: 8 },
  { id: 14, name: "Mewat", state: 8 },
  { id: 15, name: "Palwal", state: 8 },
  { id: 16, name: "Panchkula", state: 8 },
  { id: 17, name: "Panipat", state: 8 },
  { id: 18, name: "Rewari", state: 8 },
  { id: 19, name: "Rohtak", state: 8 },
  { id: 20, name: "Sirsa", state: 8 },
  { id: 21, name: "Sonipat", state: 8 },
  { id: 22, name: "Yamunanagar", state: 8 },
  { id: 1, name: "Bilaspur", state: 9 },
  { id: 2, name: "Chamba", state: 9 },
  { id: 3, name: "Hamirpur", state: 9 },
  { id: 4, name: "Kangra", state: 9 },
  { id: 5, name: "Kinnaur", state: 9 },
  { id: 6, name: "Kullu", state: 9 },
  { id: 7, name: "Lahaul Spiti", state: 9 },
  { id: 8, name: "Mandi", state: 9 },
  { id: 9, name: "Shimla", state: 9 },
  { id: 10, name: "Sirmaur", state: 9 },
  { id: 11, name: "Solan", state: 9 },
  { id: 12, name: "Una", state: 9 },
  { id: 1, name: "Bokaro", state: 11 },
  { id: 2, name: "Chatra", state: 11 },
  { id: 3, name: "Deoghar", state: 11 },
  { id: 4, name: "Dhanbad", state: 11 },
  { id: 5, name: "Dumka", state: 11 },
  { id: 6, name: "East Singhbhum", state: 11 },
  { id: 7, name: "Garhwa", state: 11 },
  { id: 8, name: "Giridih", state: 11 },
  { id: 9, name: "Godda", state: 11 },
  { id: 10, name: "Gumla", state: 11 },
  { id: 11, name: "Hazaribagh", state: 11 },
  { id: 12, name: "Jamtara", state: 11 },
  { id: 13, name: "Khunti", state: 11 },
  { id: 14, name: "Koderma", state: 11 },
  { id: 15, name: "Latehar", state: 11 },
  { id: 16, name: "Lohardaga", state: 11 },
  { id: 17, name: "Pakur", state: 11 },
  { id: 18, name: "Palamu", state: 11 },
  { id: 19, name: "Ramgarh", state: 11 },
  { id: 20, name: "Ranchi", state: 11 },
  { id: 21, name: "Sahebganj", state: 11 },
  { id: 22, name: "Seraikela Kharsawan", state: 11 },
  { id: 23, name: "Simdega", state: 11 },
  { id: 24, name: "West Singhbhum", state: 11 },
  { id: 1, name: "Anantnag", state: 10 },
  { id: 2, name: "Bandipora", state: 10 },
  { id: 3, name: "Baramulla", state: 10 },
  { id: 4, name: "Budgam", state: 10 },
  { id: 5, name: "Doda", state: 10 },
  { id: 6, name: "Ganderbal", state: 10 },
  { id: 7, name: "Jammu", state: 10 },
  { id: 8, name: "Kargil", state: 10 },
  { id: 9, name: "Kathua", state: 10 },
  { id: 10, name: "Kishtwar", state: 10 },
  { id: 11, name: "Kulgam", state: 10 },
  { id: 12, name: "Kupwara", state: 10 },
  { id: 13, name: "Leh", state: 10 },
  { id: 14, name: "Poonch", state: 10 },
  { id: 15, name: "Pulwama", state: 10 },
  { id: 16, name: "Rajouri", state: 10 },
  { id: 17, name: "Ramban", state: 10 },
  { id: 18, name: "Reasi", state: 10 },
  { id: 19, name: "Samba", state: 10 },
  { id: 20, name: "Shopian", state: 10 },
  { id: 21, name: "Srinagar", state: 10 },
  { id: 22, name: "Udhampur", state: 10 },
]
selectedState : any = "";
selectedCity : any = "";

dropdownCity: any = [];

populateCity(value) {
  this.dropdownCity = this.City.filter(i => i.state == value);
}


}
